apiVersion: v2
name: onion-inference-engine
description: Standalone tenant-deployed Onion model plane
type: application
version: 0.1.5
appVersion: "0.1.13"
home: https://github.com/caglarsubas/llm_inference_engine
sources:
  - https://github.com/caglarsubas/llm_inference_engine
keywords:
  - inference
  - model-gateway
  - openshift
  - onion
maintainers:
  - name: Onion Model Plane Team
annotations:
  openshift.io/display-name: "Onion Inference Engine"
