{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "orchestra-inference-engine.fullname" . }}
  {{- with .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "orchestra-inference-engine.labels" . | nindent 4 }}
spec:
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orchestra-inference-engine.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ ternary "https" "http" .Values.serverTls.enabled }}
      path: /v1/metrics
      {{- if .Values.serverTls.enabled }}
      scheme: https
      tlsConfig:
        serverName: {{ .Values.metrics.serviceMonitor.tls.serverName | quote }}
        ca:
          secret:
            name: {{ .Values.metrics.serviceMonitor.tls.caSecretName | quote }}
            key: {{ .Values.metrics.serviceMonitor.tls.caKey | quote }}
        {{- if .Values.serverTls.requireClientCertificate }}
        cert:
          secret:
            name: {{ .Values.metrics.serviceMonitor.tls.clientCertificateSecretName | quote }}
            key: {{ .Values.metrics.serviceMonitor.tls.clientCertificateKey | quote }}
        keySecret:
          name: {{ .Values.metrics.serviceMonitor.tls.clientCertificateSecretName | quote }}
          key: {{ .Values.metrics.serviceMonitor.tls.clientPrivateKeyKey | quote }}
        {{- end }}
      {{- end }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
